package Clases;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;

public class ContinuarRegistro extends javax.swing.JFrame {

    RegistrarAlumno r = new RegistrarAlumno();

    String ruta = "src/IMG/fondoblanco.jpg";
    public int Validacion = 0;
    public String D[][] = new String[2][7];

    String ID = r.rey[1][0];
    Metodos m = new Metodos();

    public ContinuarRegistro() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Continuar Con El Registro");

        ImageIcon FondoDePantalla = new ImageIcon(ruta);
        Icon icono = new ImageIcon(FondoDePantalla.getImage().getScaledInstance(Bakground.getWidth(),
                Bakground.getHeight(), Image.SCALE_DEFAULT));
        Bakground.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        NombreP = new javax.swing.JTextField();
        IDPadre = new javax.swing.JTextField();
        DireccionP = new javax.swing.JTextField();
        TelefonoP = new javax.swing.JTextField();
        NombreM = new javax.swing.JTextField();
        IDMadre = new javax.swing.JTextField();
        DireccionM = new javax.swing.JTextField();
        TelefonoM = new javax.swing.JTextField();
        NombreA = new javax.swing.JTextField();
        IDAcudiente = new javax.swing.JTextField();
        DireccionA = new javax.swing.JTextField();
        TelefonoA = new javax.swing.JTextField();
        EPS = new javax.swing.JTextField();
        InstitucuionAnterior = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Bakground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFORMACION DE PADRES Y ACUDIENTES.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1000, -1));

        NombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(NombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 30));

        IDPadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(IDPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 200, 30));
        getContentPane().add(DireccionP, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 200, 30));

        TelefonoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(TelefonoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 200, 30));

        NombreM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(NombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 200, 30));

        IDMadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(IDMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 200, 30));
        getContentPane().add(DireccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 200, 30));

        TelefonoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(TelefonoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 200, 30));

        NombreA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(NombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 200, 30));

        IDAcudiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(IDAcudiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 200, 30));
        getContentPane().add(DireccionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 200, 30));

        TelefonoA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(TelefonoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 200, 30));

        EPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(EPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 550, 200, 30));

        InstitucuionAnterior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(InstitucuionAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 200, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 100, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NOMBRE.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("No IDENTIFICACIÓN.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("DIRECCIÓN.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("TELEFONO.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NOMBRE.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("No IDENTIFICACIÓN.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DIRECCIÓN.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("TELEFONO.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("NOMBRE.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("No IDENTIFICACIÓN.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("DIRECCIÓN.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("TELEFONO.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("E.P.S");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("INSTITUCION ANTERIOR.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel16.setText("ACUDIENTE:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel17.setText("PADRE:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel18.setText("MADRE:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jButton2.setText("x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));
        getContentPane().add(Bakground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        eliminar();
        this.setVisible(false);
        InterfazPrincipal I = new InterfazPrincipal();
        I.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //esta variable contiene la informacion de esta ventana.
        Validacion = 0;

        D[0][0] = NombreP.getText().trim();
        if (D[0][0].equals("")) {
            NombreP.setBackground(Color.red);
            Validacion++;
        }
        D[0][1] = IDPadre.getText().trim();
        if (D[0][1].equals("")) {
            IDPadre.setBackground(Color.red);
            Validacion++;
        }
        D[0][2] = DireccionP.getText().trim();
        if (D[0][2].equals("")) {
            DireccionP.setBackground(Color.red);
            Validacion++;
        }
        D[0][3] = DireccionM.getText().trim();
        if (D[0][3].equals("")) {
            DireccionM.setBackground(Color.red);
            Validacion++;
        }
        D[0][4] = EPS.getText().trim();
        if (D[0][4].equals("")) {
            EPS.setBackground(Color.red);
            Validacion++;
        }
        D[0][5] = InstitucuionAnterior.getText().trim();
        if (D[0][5].equals("")) {
            InstitucuionAnterior.setBackground(Color.red);
            Validacion++;
        }
        D[0][6] = IDMadre.getText().trim();
        if (D[0][6].equals("")) {
            IDMadre.setBackground(Color.red);
            Validacion++;
        }
        D[1][0] = TelefonoP.getText().trim();
        if (D[1][0].equals("")) {
            TelefonoP.setBackground(Color.red);
            Validacion++;
        }
        D[1][1] = TelefonoM.getText().trim();
        if (D[1][1].equals("")) {
            TelefonoM.setBackground(Color.red);
            Validacion++;
        }
        D[1][2] = NombreM.getText().trim();
        if (D[1][2].equals("")) {
            NombreM.setBackground(Color.red);
            Validacion++;
        }
        if (Validacion != 0) {
            JOptionPane.showMessageDialog(null,
                    "Los campos marcados con rojo son obligatorios.");
        }

        D[1][3] = NombreA.getText().trim();
        D[1][4] = DireccionA.getText().trim();
        D[1][5] = TelefonoA.getText().trim();
        D[1][6] = IDAcudiente.getText().trim();

        if (Validacion == 0) {

            try {

                Connection cn = ClaseMetodos.conectar();
                PreparedStatement pst = cn.prepareStatement("update alumnos set Padre = ?, Cedula_Padre = ?,"
                        + " Direccion_Padre = ?, Telefono_Padre = ?, Madre = ?, Cedula_Madre = ?, Direccion_Madre = ?,"
                        + "Telefono_Madre = ?, Acudiente = ?, Direccion_Acudiente = ?, Cedula_Acudiente = ?, Telefono_Acudiente = ? "
                        + ",InstitucionAnterior = ?, EPS = ? where Documento = '" + ID+"'");//14

                pst.setString(1, NombreP.getText().trim());
                pst.setString(2, IDPadre.getText().trim());
                pst.setString(3, DireccionP.getText().trim());
                pst.setString(4, TelefonoP.getText().trim());
                pst.setString(5, NombreM.getText().trim());
                pst.setString(6, IDMadre.getText().trim());
                pst.setString(7, DireccionM.getText().trim());
                pst.setString(8, TelefonoM.getText().trim());
                pst.setString(9, NombreA.getText().trim());
                pst.setString(10, DireccionA.getText().trim());
                pst.setString(11, IDAcudiente.getText().trim());
                pst.setString(12, TelefonoA.getText().trim());
                pst.setString(13, InstitucuionAnterior.getText().trim());
                pst.setString(14, EPS.getText().trim());

                pst.executeLargeUpdate();
                cn.close();
                
            } catch (SQLException e) {
                System.out.println("este fue un error al registrar Alumno " + ID + " " + e);
                eliminar();
            }

            
            JOptionPane.showMessageDialog(null, "Registro exitoso.");
            terminado();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void soloLetras(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soloLetras
        // TODO add your handling code here:
        m.SoloLetras(evt);
    }//GEN-LAST:event_soloLetras

    private void soloNumeros(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soloNumeros
        // TODO add your handling code here:
        m.SoloNumeros(evt);
    }//GEN-LAST:event_soloNumeros

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContinuarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContinuarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContinuarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContinuarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContinuarRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bakground;
    public javax.swing.JTextField DireccionA;
    public javax.swing.JTextField DireccionM;
    public javax.swing.JTextField DireccionP;
    public javax.swing.JTextField EPS;
    public javax.swing.JTextField IDAcudiente;
    public javax.swing.JTextField IDMadre;
    public javax.swing.JTextField IDPadre;
    public javax.swing.JTextField InstitucuionAnterior;
    public javax.swing.JTextField NombreA;
    public javax.swing.JTextField NombreM;
    public javax.swing.JTextField NombreP;
    public javax.swing.JTextField TelefonoA;
    public javax.swing.JTextField TelefonoM;
    public javax.swing.JTextField TelefonoP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    public void eliminar() {
        try {
            Connection cn = ClaseMetodos.conectar();
            //esta linea de codigo da las instrucciones a la base de datos para eliminar un elemento
            PreparedStatement pst = cn.prepareStatement("delete from alumnos where Documento = ?");

            pst.setString(1, ID);
            pst.executeUpdate();
            cn.close();
        } catch (SQLException e) {
            System.out.println("error al borrar registro " + e);
        }
    }

    public void terminado() {
        this.setVisible(false);
        RegistrarAlumno R = new RegistrarAlumno();
        R.setVisible(false);
        InterfazPrincipal I = new InterfazPrincipal();
        I.setVisible(true);
    }
}
