package Clases;

import java.awt.*;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.*;

public class ModificarInformacion extends javax.swing.JFrame {

    String ruta = "src/IMG/06A3A5-imagen.png";

    //estas variables refieren a tipo de documento y sexo o genero.
    public static String ti, se, instruccion = "", user_update = "";
    int edad, CantFilas = 12, Contador, id;
    public static int paso = 0;
    String b[] = new String[CantFilas], datoGrado = "";
    Metodos m = new Metodos();
    boolean ComboActivo = false;

    public ModificarInformacion() {
        initComponents();

        setLocationRelativeTo(null);
        setTitle("PRECAUSIÓN ESTÁ MODIFICANDO DATOS DELICADOS...");

        ImageIcon FondoDePantalla = new ImageIcon(ruta);
        Icon icono = new ImageIcon(FondoDePantalla.getImage().getScaledInstance(Bakground.getWidth(),
                Bakground.getHeight(), Image.SCALE_DEFAULT));
        Bakground.setIcon(icono);
        this.repaint();

        //aca se colocan las imagenes en los Stiquer
        ImageIcon Stiq = new ImageIcon("src/IMG/CorregirDatos.png");
        Icon icono2 = new ImageIcon(Stiq.getImage().getScaledInstance(Stiquer.getWidth(),
                Stiquer.getHeight(), Image.SCALE_DEFAULT));
        Stiquer.setIcon(icono2);

        Modificar.setEnabled(false);
        GradoSelet.setVisible(false);
        veintidos.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nueve = new javax.swing.JTextField();
        diez = new javax.swing.JTextField();
        once = new javax.swing.JTextField();
        doce = new javax.swing.JTextField();
        trece = new javax.swing.JTextField();
        catorce = new javax.swing.JTextField();
        quince = new javax.swing.JTextField();
        dieciseis = new javax.swing.JTextField();
        veintiuno = new javax.swing.JTextField();
        dieciocho = new javax.swing.JTextField();
        diecinueve = new javax.swing.JTextField();
        veinte = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        seis = new javax.swing.JTextField();
        siete = new javax.swing.JTextField();
        ocho = new javax.swing.JTextField();
        uno = new javax.swing.JTextField();
        dos = new javax.swing.JTextField();
        tres = new javax.swing.JTextField();
        diecisiete = new javax.swing.JTextField();
        veintidos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        TI = new javax.swing.JCheckBox();
        F = new javax.swing.JCheckBox();
        M = new javax.swing.JCheckBox();
        RC = new javax.swing.JCheckBox();
        CheckModificar = new javax.swing.JCheckBox();
        GradoSelet = new javax.swing.JComboBox<>();
        Stiquer = new javax.swing.JLabel();
        veintiuno1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        veintiuno2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Bakground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 249, 250));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CORREGIR INFORMACION.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 940, -1));

        jButton2.setText("x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Enter(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 125, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 249, 250));
        jLabel3.setText("ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 108, -1, -1));

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 125, 117, 30));

        nueve.setBackground(new java.awt.Color(204, 204, 255));
        nueve.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nueve.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 193, 30));

        diez.setBackground(new java.awt.Color(204, 204, 255));
        diez.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(diez, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 172, 30));

        once.setBackground(new java.awt.Color(204, 204, 255));
        once.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        once.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(once, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 168, 30));

        doce.setBackground(new java.awt.Color(204, 204, 255));
        doce.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        doce.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(doce, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 168, 30));

        trece.setBackground(new java.awt.Color(204, 204, 255));
        trece.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        trece.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(trece, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 425, 193, 30));

        catorce.setBackground(new java.awt.Color(204, 204, 255));
        catorce.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(catorce, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 425, 172, 30));

        quince.setBackground(new java.awt.Color(204, 204, 255));
        quince.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quince.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(quince, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 425, 168, 30));

        dieciseis.setBackground(new java.awt.Color(204, 204, 255));
        dieciseis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dieciseis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(dieciseis, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 425, 168, 30));

        veintiuno.setBackground(new java.awt.Color(204, 204, 255));
        veintiuno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(veintiuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 215, 170, 30));

        dieciocho.setBackground(new java.awt.Color(204, 204, 255));
        dieciocho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(dieciocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 172, 30));

        diecinueve.setBackground(new java.awt.Color(204, 204, 255));
        diecinueve.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        diecinueve.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(diecinueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 168, 30));

        veinte.setBackground(new java.awt.Color(204, 204, 255));
        veinte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        veinte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(veinte, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 168, 30));

        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 630, 300, 40));

        seis.setBackground(new java.awt.Color(204, 204, 255));
        seis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        seis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 172, 30));

        siete.setBackground(new java.awt.Color(204, 204, 255));
        siete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        siete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 168, 30));

        ocho.setBackground(new java.awt.Color(204, 204, 255));
        ocho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ocho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 168, 30));

        uno.setBackground(new java.awt.Color(204, 204, 255));
        uno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 215, 193, 30));

        dos.setBackground(new java.awt.Color(204, 204, 255));
        dos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 215, 172, 30));

        tres.setBackground(new java.awt.Color(204, 204, 255));
        tres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 215, 168, 30));

        diecisiete.setBackground(new java.awt.Color(204, 204, 255));
        diecisiete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        diecisiete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(diecisiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 193, 30));

        veintidos.setBackground(new java.awt.Color(204, 204, 255));
        veintidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        veintidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Desaparece(evt);
            }
        });
        getContentPane().add(veintidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 215, 190, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 249, 250));
        jLabel1.setText("GENERO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 249, 250));
        jLabel4.setText("NOMBRES:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 249, 250));
        jLabel5.setText("DOCUMENTO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 249, 250));
        jLabel6.setText("TIPO DE DOCUMENTO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 249, 250));
        jLabel7.setText("VALOR MATRICULA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(251, 249, 250));
        jLabel8.setText("VALOR PENSION:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(251, 249, 250));
        jLabel9.setText("NOMBRE PADRE:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(251, 249, 250));
        jLabel10.setText("DIRECCION PADRE:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 249, 250));
        jLabel11.setText("C.C PADRE:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(251, 249, 250));
        jLabel12.setText("TELEFONO PADRE:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(251, 249, 250));
        jLabel13.setText("NOMBRE MADRE:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(251, 249, 250));
        jLabel14.setText("C.C MADRE:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 405, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(251, 249, 250));
        jLabel15.setText("DIRECCION MADRE:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 405, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(251, 249, 250));
        jLabel16.setText("TELEFONO MADRE:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 405, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(251, 249, 250));
        jLabel17.setText("NOMBRE ACUDIENTE:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 405, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(251, 249, 250));
        jLabel18.setText("C.C ACUDIENTE:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(251, 249, 250));
        jLabel19.setText("DIRECCION ACUDIENTE:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(251, 249, 250));
        jLabel20.setText("TELEFONO ACUDIENTE:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(251, 249, 250));
        jLabel21.setText("EDAD:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(251, 249, 250));
        jLabel22.setText("RH:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 30, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(251, 249, 250));
        jLabel23.setText("GRADO:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(251, 249, 250));
        jLabel25.setText("APELLIDOS:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        TI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TI.setForeground(new java.awt.Color(251, 249, 250));
        TI.setText("T.I");
        TI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIActionPerformed(evt);
            }
        });
        getContentPane().add(TI, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 360, -1, -1));

        F.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        F.setForeground(new java.awt.Color(251, 249, 250));
        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        getContentPane().add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, -1, -1));

        M.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        M.setForeground(new java.awt.Color(251, 249, 250));
        M.setText("M");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        getContentPane().add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, -1, -1));

        RC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RC.setForeground(new java.awt.Color(251, 249, 250));
        RC.setText("R.C");
        RC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCActionPerformed(evt);
            }
        });
        getContentPane().add(RC, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, -1, -1));

        CheckModificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CheckModificar.setForeground(new java.awt.Color(251, 249, 250));
        CheckModificar.setText("Modificar Datos");
        CheckModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckModificarActionPerformed(evt);
            }
        });
        getContentPane().add(CheckModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 180, 50));

        GradoSelet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Grado", "Maternal", "Parvulo", "Pre-Jardin", "Jardin", "Trancision", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto" }));
        getContentPane().add(GradoSelet, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 210, 170, 30));
        getContentPane().add(Stiquer, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 100, 100));

        veintiuno1.setBackground(new java.awt.Color(204, 204, 255));
        veintiuno1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(veintiuno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 280, 193, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(251, 249, 250));
        jLabel24.setText("EPS:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, -1, -1));

        veintiuno2.setBackground(new java.awt.Color(204, 204, 255));
        veintiuno2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(veintiuno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 193, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(251, 249, 250));
        jLabel26.setText("Ins. Anterior:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        getContentPane().add(Bakground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (paso == 1) {
            this.setVisible(false);
        } else if (paso == 0) {

            InterfazPrincipal I = new InterfazPrincipal();
            I.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        TI.setEnabled(false);
        RC.setEnabled(false);
        F.setEnabled(false);
        M.setEnabled(false);
            try {
                //Conexion con base de datos.
                Connection cn = ClaseMetodos.conectar();

                //esta linea de codigo le da las intrucciones a la base de datos
                PreparedStatement pst = cn.prepareStatement("select * from alumnos where Documento = ?");

                pst.setString(1, ID.getText());
                ResultSet rs = pst.executeQuery();
                // con este codigo intento obtener los balores almacenados en la base de datos registro
                if (rs.next()) {

                    uno.setText(rs.getString("Apellidos"));
                    dos.setText(rs.getString("Nombres"));
                    tres.setText(rs.getString("Documento"));
                    ti = rs.getString("Tipo_Documento");
                    if (ti.equals("TI")) {
                        TI.setSelected(true);
                        RC.setSelected(false);
                    } else if (ti.equals("RC")) {
                        RC.setSelected(true);
                        TI.setSelected(false);
                    }
                    se = (rs.getString("Sexo"));
                    if (se.equals("F")) {
                        F.setSelected(true);
                        M.setSelected(false);
                    } else if (se.equals("M")) {
                        M.setSelected(true);
                        F.setSelected(false);
                    }
                    seis.setText(rs.getString("Matricula"));
                    siete.setText(rs.getString("Valor_Pension"));
                    ocho.setText(rs.getString("Padre"));
                    nueve.setText(rs.getString("Cedula_Padre"));
                    diez.setText(rs.getString("Direccion_Padre"));
                    once.setText(rs.getString("Telefono_Padre"));
                    doce.setText(rs.getString("Madre"));
                    trece.setText(rs.getString("Cedula_Madre"));
                    catorce.setText(rs.getString("Direccion_Madre"));
                    quince.setText(rs.getString("Telefono_Madre"));
                    dieciseis.setText(rs.getString("Acudiente"));
                    diecisiete.setText(rs.getString("Cedula_Acudiente"));
                    dieciocho.setText(rs.getString("Direccion_Acudiente"));
                    diecinueve.setText(rs.getString("Telefono_Acudiente"));
                    veinte.setText(rs.getString("Edad"));
                    veintiuno.setText(rs.getString("RH"));
                    veintidos.setText(rs.getString("Grado"));
                    veintiuno1.setText(rs.getString("InstitucionAnterior"));
                    veintiuno2.setText(rs.getString("EPS"));

                } else {
                    JOptionPane.showMessageDialog(null, "No coincide el numero: "
                            + ID.getText().trim() + " \n con los datos almacenados");

                    nueve.setText("");
                    dieciocho.setText("");
                    veintiuno.setText("");
                    diez.setText("");
                    once.setText("");
                    quince.setText("");
                    doce.setText("");
                    catorce.setText("");
                    trece.setText("");
                    dieciseis.setText("");
                    veinte.setText("");
                    uno.setText("");
                    dos.setText("");
                    tres.setText("");
                    seis.setText("");
                    siete.setText("");
                    ocho.setText("");
                    diecisiete.setText("");
                    diecinueve.setText("");
                    veintidos.setText("");
                    veintiuno1.setText("");
                    veintiuno2.setText("");
                }
            } catch (Exception e) {
                System.out.println("esta cosa no quiere conectar " + e);

            }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        CantFilas = 10;
        Contador = 0;

        b[0] = uno.getText().trim();
        b[1] = dos.getText().trim();
        b[2] = tres.getText().trim();
        b[3] = seis.getText().trim();
        b[4] = siete.getText().trim();
        b[5] = ocho.getText().trim();
        b[6] = doce.getText().trim();
        b[7] = veinte.getText().trim();
        b[8] = veintiuno.getText().trim();
        b[9] = veintidos.getText().trim();
        b[10] = veintiuno.getText().trim();
        b[11] = veintiuno.getText().trim();

        if (b[0].equals("")) {
            uno.setBackground(Color.red);
            uno.setForeground(Color.white);
            Contador++;
        }
        if (b[1].equals("")) {
            dos.setBackground(Color.red);
            dos.setForeground(Color.white);
            Contador++;
        }
        if (b[2].equals("")) {
            tres.setBackground(Color.red);
            tres.setForeground(Color.white);
            Contador++;
        }
        if (b[3].equals("")) {
            seis.setBackground(Color.red);
            seis.setForeground(Color.white);
            Contador++;
        }
        if (b[4].equals("")) {
            siete.setBackground(Color.red);
            siete.setForeground(Color.white);
            Contador++;
        }
        if (b[5].equals("")) {
            ocho.setBackground(Color.red);
            ocho.setForeground(Color.white);
            Contador++;
        }
        if (b[6].equals("")) {
            doce.setBackground(Color.red);
            doce.setForeground(Color.white);
            Contador++;
        }
        if (b[7].equals("")) {
            veinte.setBackground(Color.red);
            veinte.setForeground(Color.white);
            Contador++;
        }
        if (b[8].equals("")) {
            veintiuno.setBackground(Color.red);
            veintiuno.setForeground(Color.white);
            Contador++;
        }
        if (b[9].equals("")) {
            veintidos.setBackground(Color.red);
            veintidos.setForeground(Color.white);
            Contador++;
        }
        if (b[10].equals("")) {
            veintiuno1.setBackground(Color.red);
            veintiuno1.setForeground(Color.white);
            Contador++;
        }
        if (b[11].equals("")) {
            veintiuno2.setBackground(Color.red);
            veintiuno2.setForeground(Color.white);
            Contador++;
        }
        if (TI.isSelected() & RC.isSelected()) {
            TI.setSelected(false);
            RC.setSelected(false);
        }
        if (M.isSelected() & F.isSelected()) {
            M.setSelected(false);
            F.setSelected(false);
        }
        if (!M.isSelected() & !F.isSelected()) {
            Contador++;
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar el genero del estudiante.");
        }
        if (!TI.isSelected() & !RC.isSelected()) {
            Contador++;
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar el tipo de documento del estudiante.");
        }
        if (ComboActivo == true) {
            datoGrado = GradoSelet.getSelectedItem().toString();
        } else {
            datoGrado = veintidos.getText().trim();
        }

        //se modifican Datos
        if (Contador == 0 & !"".equals(datoGrado) & !"Seleccione Grado".equals(datoGrado)) {
            try {
                try (
                        //este codigo conecta con la base de datos
                        Connection cn = ClaseMetodos.conectar()) {
                    //esta linea de codigo da las instrucciones a la base de datos
                    PreparedStatement pst = cn.prepareStatement(
                            "update alumnos set Apellidos = ?, Nombres = ?, "
                            + "Documento = ?, Tipo_Documento = ?, "
                            + "Sexo = ?, Padre = ?, Cedula_Padre = ?, "
                            + "Direccion_Padre = ?, Telefono_Padre = ?, Madre = ?, "
                            + "Cedula_Madre = ?, Direccion_Madre = ?, "
                            + "Telefono_Madre = ?, Acudiente = ?, Direccion_Acudiente = ?, "
                            + "Cedula_Acudiente = ?, "
                            + "Telefono_Acudiente = ?, Edad = ?, RH = ?, Valor_Pension = ?, "
                            + "Grado = ?, Matricula = ?, InstitucionAnterior = ?, EPS = ? WHERE Documento = '"
                            + ID.getText().trim() + "'");//24

                    pst.setString(1, uno.getText().trim());
                    pst.setString(2, dos.getText().trim());
                    pst.setString(3, tres.getText().trim());
                    if (TI.isSelected() & !RC.isSelected()) {
                        ti = "TI";
                    } else if (!TI.isSelected() & RC.isSelected()) {
                        ti = "RC";
                    }

                    pst.setString(4, ti);
                    if (M.isSelected() & !F.isSelected()) {
                        se = "M";
                    } else if (!M.isSelected() & F.isSelected()) {
                        se = "F";
                    }
                    pst.setString(5, se);

                    pst.setString(6, ocho.getText().trim());
                    pst.setString(7, nueve.getText().trim());
                    pst.setString(8, diez.getText().trim());
                    pst.setString(9, once.getText().trim());
                    pst.setString(10, doce.getText().trim());
                    pst.setString(11, trece.getText().trim());
                    pst.setString(12, catorce.getText().trim());
                    pst.setString(13, quince.getText().trim());
                    pst.setString(14, dieciseis.getText().trim());
                    pst.setString(15, dieciocho.getText().trim());
                    pst.setString(16, diecisiete.getText().trim());
                    pst.setString(17, diecinueve.getText().trim());
                    edad = Integer.parseInt(veinte.getText().trim());
                    pst.setInt(18, edad);
                    pst.setString(19, veintiuno.getText().trim());
                    int pension = Integer.parseInt(siete.getText().trim());

                    pst.setInt(20, pension);
                    pst.setString(21, datoGrado);
                    int matricula = Integer.parseInt(seis.getText().trim());
                    pst.setInt(22, matricula);
                    pst.setString(23, veintiuno1.getText().trim());
                    pst.setString(24, veintiuno2.getText().trim());
                    pst.executeUpdate();
                }

                JOptionPane.showMessageDialog(null, "MODIFICACION EXITOSA...");

                ClaseMetodos c = new ClaseMetodos();
                if (paso == 0) {
                    this.setVisible(false);
                    c.Salir();
                } else {
                    this.setVisible(false);
                }
            } catch (SQLException e) {
                System.out.println("es aqi");
                System.out.println("no hay conexion " + e);

            }
        } else {
            if ("Seleccione Grado".equals(datoGrado) || "".equals(datoGrado)) {
                JOptionPane.showMessageDialog(null, "Seleccione Grado");
            }
            JOptionPane.showMessageDialog(null,
                    "Los campos marcados con rojo \n no pueden estar vacios. ");

        }


    }//GEN-LAST:event_ModificarActionPerformed

    private void CheckModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckModificarActionPerformed
        // TODO add your handling code here:
        if (CheckModificar.isSelected()) {
            JOptionPane.showMessageDialog(null,
                    "Los datos que esta por modificar no se podran recuperar. \n "
                    + "debe estar seguro cuando pulse el boton.");
            Modificar.setEnabled(true);
            TI.setEnabled(true);
            RC.setEnabled(true);
            F.setEnabled(true);
            M.setEnabled(true);

            nueve.setBackground(Color.cyan);
            dieciocho.setBackground(Color.cyan);
            veintiuno.setBackground(Color.cyan);
            diez.setBackground(Color.cyan);
            once.setBackground(Color.cyan);
            quince.setBackground(Color.cyan);
            doce.setBackground(Color.cyan);
            catorce.setBackground(Color.cyan);
            trece.setBackground(Color.cyan);
            dieciseis.setBackground(Color.cyan);
            veinte.setBackground(Color.cyan);
            uno.setBackground(Color.cyan);
            dos.setBackground(Color.cyan);
            tres.setBackground(Color.cyan);
            seis.setBackground(Color.cyan);
            siete.setBackground(Color.cyan);
            ocho.setBackground(Color.cyan);
            diecisiete.setBackground(Color.cyan);
            diecinueve.setBackground(Color.cyan);
            veintidos.setBackground(Color.cyan);
            veintiuno1.setBackground(Color.cyan);
            veintiuno2.setBackground(Color.cyan);

            jButton1.setEnabled(false);

        } else if (!CheckModificar.isSelected()) {
            Modificar.setEnabled(false);
            TI.setEnabled(false);
            RC.setEnabled(false);
            F.setEnabled(false);
            M.setEnabled(false);

            jButton1.setEnabled(true);

            nueve.setBackground(Color.WHITE);
            dieciocho.setBackground(Color.WHITE);
            veintiuno.setBackground(Color.WHITE);
            diez.setBackground(Color.WHITE);
            once.setBackground(Color.WHITE);
            quince.setBackground(Color.WHITE);
            doce.setBackground(Color.WHITE);
            catorce.setBackground(Color.WHITE);
            trece.setBackground(Color.WHITE);
            dieciseis.setBackground(Color.WHITE);
            veinte.setBackground(Color.WHITE);
            uno.setBackground(Color.WHITE);
            dos.setBackground(Color.WHITE);
            tres.setBackground(Color.WHITE);
            seis.setBackground(Color.WHITE);
            siete.setBackground(Color.WHITE);
            ocho.setBackground(Color.WHITE);
            diecisiete.setBackground(Color.WHITE);
            diecinueve.setBackground(Color.WHITE);
            veintidos.setBackground(Color.WHITE);
            veintiuno1.setBackground(Color.WHITE);
            veintiuno2.setBackground(Color.WHITE);
            
            
            nueve.setText("");
            dieciocho.setText("");
            veintiuno.setText("");
            diez.setText("");
            once.setText("");
            quince.setText("");
            doce.setText("");
            catorce.setText("");
            trece.setText("");
            dieciseis.setText("");
            veinte.setText("");
            uno.setText("");
            dos.setText("");
            tres.setText("");
            seis.setText("");
            siete.setText("");
            ocho.setText("");
            diecisiete.setText("");
            diecinueve.setText("");
            veintidos.setText("");
            veintiuno1.setText("");
            veintiuno2.setText("");
        }
    }//GEN-LAST:event_CheckModificarActionPerformed

    private void TIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIActionPerformed
        // TODO add your handling code here:
        if (TI.isSelected()) {
            RC.setEnabled(false);
            ti = "TI";
        } else {
            RC.setEnabled(true);
        }
        if (TI.isSelected() & RC.isSelected()) {
            TI.setSelected(false);
            RC.setSelected(false);
        }
    }//GEN-LAST:event_TIActionPerformed

    private void RCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCActionPerformed
        // TODO add your handling code here:
        if (RC.isSelected()) {
            TI.setEnabled(false);
            ti = "RC";
        } else {
            TI.setEnabled(true);
        }
        if (TI.isSelected() & RC.isSelected()) {
            TI.setSelected(false);
            RC.setSelected(false);
        }
    }//GEN-LAST:event_RCActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
        if (F.isSelected()) {
            M.setEnabled(false);
            se = "F";
        } else {
            M.setEnabled(true);
        }
        if (M.isSelected() & F.isSelected()) {
            M.setSelected(false);
            F.setSelected(false);
        }
    }//GEN-LAST:event_FActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        // TODO add your handling code here:
        if (M.isSelected()) {
            F.setEnabled(false);
            se = "M";
        } else {
            F.setEnabled(true);
        }
        if (M.isSelected() & F.isSelected()) {
            M.setSelected(false);
            F.setSelected(false);
        }
    }//GEN-LAST:event_MActionPerformed

    private void soloNumeros(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soloNumeros
        // TODO add your handling code here:
        m.SoloNumeros(evt);
    }//GEN-LAST:event_soloNumeros

    private void soloLetras(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soloLetras
        // TODO add your handling code here:
        m.SoloLetras(evt);
    }//GEN-LAST:event_soloLetras

    private void Enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Enter
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            TI.setEnabled(false);
            RC.setEnabled(false);
            F.setEnabled(false);
            M.setEnabled(false);
            try {
                //Conexion con base de datos.
                Connection cn = ClaseMetodos.conectar();

                //esta linea de codigo le da las intrucciones a la base de datos
                PreparedStatement pst = cn.prepareStatement("select * from alumnos where Documento = ?");

                pst.setString(1, ID.getText());
                ResultSet rs = pst.executeQuery();
                // con este codigo intento obtener los balores almacenados en la base de datos registro
                if (rs.next()) {

                    uno.setText(rs.getString("Apellidos"));
                    dos.setText(rs.getString("Nombres"));
                    tres.setText(rs.getString("Documento"));
                    ti = rs.getString("Tipo_Documento");
                    if (ti.equals("TI")) {
                        TI.setSelected(true);
                        RC.setSelected(false);
                    } else if (ti.equals("RC")) {
                        RC.setSelected(true);
                        TI.setSelected(false);
                    }
                    se = (rs.getString("Sexo"));
                    if (se.equals("F")) {
                        F.setSelected(true);
                        M.setSelected(false);
                    } else if (se.equals("M")) {
                        M.setSelected(true);
                        F.setSelected(false);
                    }
                    seis.setText(rs.getString("Matricula"));
                    siete.setText(rs.getString("Valor_Pension"));
                    ocho.setText(rs.getString("Padre"));
                    nueve.setText(rs.getString("Cedula_Padre"));
                    diez.setText(rs.getString("Direccion_Padre"));
                    once.setText(rs.getString("Telefono_Padre"));
                    doce.setText(rs.getString("Madre"));
                    trece.setText(rs.getString("Cedula_Madre"));
                    catorce.setText(rs.getString("Direccion_Madre"));
                    quince.setText(rs.getString("Telefono_Madre"));
                    dieciseis.setText(rs.getString("Acudiente"));
                    diecisiete.setText(rs.getString("Cedula_Acudiente"));
                    dieciocho.setText(rs.getString("Direccion_Acudiente"));
                    diecinueve.setText(rs.getString("Telefono_Acudiente"));
                    veinte.setText(rs.getString("Edad"));
                    veintiuno.setText(rs.getString("RH"));
                    veintidos.setText(rs.getString("Grado"));
                    veintiuno1.setText(rs.getString("InstitucionAnterior"));
                    veintiuno2.setText(rs.getString("EPS"));

                } else {
                    JOptionPane.showMessageDialog(null, "No coincide el numero: "
                            + ID.getText().trim() + " \n con los datos almacenados");

                    nueve.setText("");
                    dieciocho.setText("");
                    veintiuno.setText("");
                    diez.setText("");
                    once.setText("");
                    quince.setText("");
                    doce.setText("");
                    catorce.setText("");
                    trece.setText("");
                    dieciseis.setText("");
                    veinte.setText("");
                    uno.setText("");
                    dos.setText("");
                    tres.setText("");
                    seis.setText("");
                    siete.setText("");
                    ocho.setText("");
                    diecisiete.setText("");
                    diecinueve.setText("");
                    veintidos.setText("");
                    veintiuno1.setText("");
                    veintiuno2.setText("");
                }
            } catch (Exception e) {
                System.out.println("esta cosa no quiere conectar " + e);

            }

        }
    }//GEN-LAST:event_Enter

    private void Desaparece(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Desaparece
        // TODO add your handling code here:

        GradoSelet.setVisible(true);
        veintidos.setVisible(false);
        veintidos.setEnabled(true);
        ComboActivo = true;
    }//GEN-LAST:event_Desaparece

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarInformacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bakground;
    private javax.swing.JCheckBox CheckModificar;
    public static javax.swing.JCheckBox F;
    private javax.swing.JComboBox<String> GradoSelet;
    public static javax.swing.JTextField ID;
    public static javax.swing.JCheckBox M;
    private javax.swing.JButton Modificar;
    public static javax.swing.JCheckBox RC;
    private javax.swing.JLabel Stiquer;
    public static javax.swing.JCheckBox TI;
    public static javax.swing.JTextField catorce;
    public static javax.swing.JTextField diecinueve;
    public static javax.swing.JTextField dieciocho;
    public static javax.swing.JTextField dieciseis;
    public static javax.swing.JTextField diecisiete;
    public static javax.swing.JTextField diez;
    public static javax.swing.JTextField doce;
    public static javax.swing.JTextField dos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField nueve;
    public static javax.swing.JTextField ocho;
    public static javax.swing.JTextField once;
    public static javax.swing.JTextField quince;
    public static javax.swing.JTextField seis;
    public static javax.swing.JTextField siete;
    public static javax.swing.JTextField trece;
    public static javax.swing.JTextField tres;
    public static javax.swing.JTextField uno;
    public static javax.swing.JTextField veinte;
    public static javax.swing.JTextField veintidos;
    public static javax.swing.JTextField veintiuno;
    public static javax.swing.JTextField veintiuno1;
    public static javax.swing.JTextField veintiuno2;
    // End of variables declaration//GEN-END:variables

    public void consulta() {
        String d = ID.getText().trim();
        if (!"".equals(d)) {

        }
    }

}
