/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class RegistrarPagoDeLibro extends javax.swing.JFrame {

    ClaseMetodos c = new ClaseMetodos();
    int cantFila = 4, contador = 0, exito = 0;
    String ruta = "src/IMG/fondoblanco.jpg", ob[] = new String[cantFila];
    String saldo = "";
    Metodos m = new Metodos();

    public RegistrarPagoDeLibro() {
        initComponents();

        setLocationRelativeTo(null);
        setTitle("Registrar Pago De Libros");

        
        //fondo de pantalla en un jLabel
        ImageIcon FondoDePantalla = new ImageIcon(ruta);
        Icon icono = new ImageIcon(FondoDePantalla.getImage().getScaledInstance(Background.getWidth(),
                Background.getHeight(), Image.SCALE_DEFAULT));
        Background.setIcon(icono);
        this.repaint();
        
        //aca se colocan las imagenes en los Stiquer
        ImageIcon Stiq = new ImageIcon("src/IMG/Libros.png");
        Icon icono2 = new ImageIcon(Stiq.getImage().getScaledInstance(Stiquer.getWidth(),
                Stiquer.getHeight(), Image.SCALE_DEFAULT));
        Stiquer.setIcon(icono2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreLibro = new javax.swing.JTextField();
        Editorial = new javax.swing.JTextField();
        Valor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consepto = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Stiquer = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 100, 30));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pago De LIbros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 580, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Titulo Del Ejemplar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 205, -1, -1));

        NombreLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloLetras(evt);
            }
        });
        getContentPane().add(NombreLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 200, 30));
        getContentPane().add(Editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, 30));

        Valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 200, 30));

        Consepto.setColumns(20);
        Consepto.setRows(5);
        jScrollPane1.setViewportView(Consepto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, 110));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Editorial:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 265, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Valor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 325, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Descripción ( Opcional* ).");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jButton1.setText("CONTINUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 100, 30));

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumeros(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Identificacion de alumno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 135, -1, -1));
        getContentPane().add(Stiquer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 100, 100));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Calendar fecha = Calendar.getInstance();
        int año = fecha.get(Calendar.YEAR);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int mes = fecha.get(Calendar.MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int min = fecha.get(Calendar.MINUTE);
        String day = c.DiaEnLetras(dia);
        String Mes = c.MesEnLetras(mes);
        String fechaS = dia + "/" + Mes + "/" + año + "/ " + hora + ":" + min;

        int Validacion = 0;
        contador = 0;
        cantFila = 4;
        ob[0] = ID.getText().trim();
        ob[1] = Valor.getText().trim();
        ob[2] = NombreLibro.getText().trim();
        ob[3] = Editorial.getText().trim();
        if (ob[0].equals("")) {
            ID.setBackground(Color.red);
            Validacion++;
        }
        if (ob[1].equals("")) {
            Validacion++;
            Valor.setBackground(Color.red);
        }
        if (ob[2].equals("")) {
            NombreLibro.setBackground(Color.red);
            Validacion++;
        }
        if (ob[3].equals("")) {
            Editorial.setBackground(Color.red);
            Validacion++;
        }
        if (Validacion != 0) {
            JOptionPane.showMessageDialog(null,
                    "Todos los campos marcados con rojo son obligatorios");
        }
        if (Validacion == 0) {
            c.pasar = 3;
            c.identificacion = ID.getText().trim();
            c.Buscar();
            
            try {
                Connection on = ClaseMetodos.conectar();
                PreparedStatement pst = on.prepareStatement(
                        "SELECT Fecha, Ingreso, Egreso, Saldo FROM contavilidad");

                ResultSet rs = pst.executeQuery();
                ResultSetMetaData rsMd = rs.getMetaData();
                int CantidadDeColumnas = rsMd.getColumnCount();
                cantFila = CantidadDeColumnas;

                while (rs.next()) {
                    for (int i = 0; i < CantidadDeColumnas; i++) {
                        ob[i] = rs.getString(i + 1);
                    }

                    contador = contador + 1;
                }

                pst = on.prepareStatement(
                        "select * from contavilidad where ID_Contabilidad =" + contador);
                rs = pst.executeQuery();

                if (rs.next()) {
                    saldo = (rs.getString("Saldo"));
                }

                exito = c.exito;
                System.out.println("este es contador " + contador);
                try (Connection cn = ClaseMetodos.conectar()) {
                    if (exito == 0) {

                        PreparedStatement pst2 = cn.prepareStatement("insert into contavilidad values "
                                + "(?,?,?, ?,?,?, ?,?,?)");
                        pst2.setInt(1, 0);
                        pst2.setString(2, fechaS);
                        pst2.setString(3, "Compra de libro: // " + Consepto.getText().trim());
                        pst2.setString(4, Valor.getText().trim());
                        pst2.setString(5, "");
                        if (contador == 0) {
                            saldo = "0";
                        }
                        int sald = Integer.parseInt(saldo.trim());
                        int pagado = Integer.parseInt(Valor.getText().trim());
                        sald = sald + pagado;
                        saldo = Integer.toString(sald);

                        pst2.setString(6, saldo);
                        pst2.setString(7, "Usuario.");
                        pst2.setString(8, ID.getText().trim());
                        String nombre = c.d[0] + " " + c.d[1] + " " + c.d[4];
                        pst2.setString(9, nombre);

                        pst2.executeUpdate();

                        on.close();

                        JOptionPane.showMessageDialog(null, "Registro exitoso.");
                        SeleccionDePago s = new SeleccionDePago();
                        s.setVisible(true);                        
                        this.setVisible(false);
                        
                    }
                }

            } catch (SQLException e) {
                Validacion++;

                System.err.println("error al registrar alumno " + e);
                JOptionPane.showMessageDialog(null, "Error en el sisteme contacte con el administrador.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SeleccionDePago s = new SeleccionDePago();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void soloNumeros(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soloNumeros
        // TODO add your handling code here:
        m.SoloNumeros(evt);
    }//GEN-LAST:event_soloNumeros

    private void soloLetras(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soloLetras
        // TODO add your handling code here:
        m.SoloLetras(evt);
    }//GEN-LAST:event_soloLetras

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagoDeLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagoDeLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagoDeLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagoDeLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPagoDeLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextArea Consepto;
    private javax.swing.JTextField Editorial;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField NombreLibro;
    private javax.swing.JLabel Stiquer;
    private javax.swing.JTextField Valor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
