
package Clases;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class RegistrarUsuario extends javax.swing.JFrame {

    Metodos m = new Metodos();

    public RegistrarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombrePago1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NombrePago2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NombrePago3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Concepto = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 35));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE USUARIO.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 760, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Usuario:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        NombrePago1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombrePago1soloLetras(evt);
            }
        });
        getContentPane().add(NombrePago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 240, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cargo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));
        getContentPane().add(NombrePago2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 240, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Contraseña:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Ingrese su contraseña:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));
        getContentPane().add(NombrePago3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 240, 30));

        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 200, 30));
        getContentPane().add(Concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombrePago1soloLetras(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombrePago1soloLetras
        // TODO add your handling code here:
        m.SoloLetras(evt);
    }//GEN-LAST:event_NombrePago1soloLetras

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int contador = 0;
        String d[] = new String[5];

        d[0] = NombrePago1.getText().trim();
        d[1] = NombrePago2.getText().trim();
        d[2] = NombrePago3.getText().trim();
        //d[3] = .getText().trim();
        d[4] = Concepto.getText().trim();


        /*if(d[3].equals("")){
            NombrePago.setBackground(Color.red);
            NombrePago.setForeground(Color.WHITE);
            contador++;
        }*/
        if (d[1].equals("")) {
            NombrePago2.setBackground(Color.red);
            NombrePago2.setForeground(Color.WHITE);
            contador++;
        }
        if (d[2].equals("")) {
            NombrePago3.setBackground(Color.red);
            NombrePago3.setForeground(Color.WHITE);
            contador++;
        }
        if (d[0].equals("")) {
            NombrePago1.setBackground(Color.red);
            NombrePago1.setForeground(Color.WHITE);
            contador++;
        }
        if (d[4].equals("")) {
            Concepto.setBackground(Color.red);
            Concepto.setForeground(Color.WHITE);
            contador++;
        }

        if (contador == 0 && d[2].equals(Login.Contraseña)) {

            try {
                //coneccion con base de datos
                Connection on = ClaseMetodos.conectar();

                //esta linea de codigo le da las intrucciones a la base de datos
                PreparedStatement pst = on.prepareStatement(
                        "select * from usuarios where Nombres ='" + d[0] + "'");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    contador++;
                }

                //para evitar que continue con las instrucciones se
                //comprueba que contador sea 0.
                if (contador == 0) {

                    //conexxion con la base de datos
                    Connection cn2 = Clases.ClaseMetodos.conectar();
                    //se dan las espesificaciones a la base de datos mysql
                    PreparedStatement pst2 = cn2.prepareStatement("insert into usuarios values "
                            + "(?,?,?, ?,?)");//5

                    pst2.setInt(1, 0);
                    pst2.setString(2, d[0]);
                    pst2.setString(3, Login.Usuario);
                    pst2.setString(4, d[4]);
                    pst2.setString(5, d[1]);

                    pst2.executeUpdate();
                    cn2.close();
                    
                    JOptionPane.showMessageDialog(null,"Registrado el usuario "+d[0]);
                    NombrePago1.setText("");
                    NombrePago2.setText("");
                    NombrePago3.setText("");
                    Concepto.setText("");
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Este usuario ya se encuentra registrado");
                    
                }
            } catch (SQLException e) {

                System.out.println("este " + e);

            }

        } else {
            JOptionPane.showMessageDialog(null, "Revise los campos y su contraseña");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        InterfazPrincipal i = new InterfazPrincipal();        
        i.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Concepto;
    private javax.swing.JTextField NombrePago1;
    private javax.swing.JTextField NombrePago2;
    private javax.swing.JTextField NombrePago3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
